In [1]:
import numpy as np
import tensorly as tl

# 1.Создание тензора

Тензоры можно представить по разному. Проще всего через его срезы.

Представим тензор $\tensor{X}$ через его срезы:
$$\newcommand{\tensor}[1]{\underline{\textbf{#1}}}
\newcommand{\M}[1]{\textbf{#1}}
\newcommand{\norm}[1]{\lVert #1 \rVert }$$
$$
   X_1 = 
   \left[
   \begin{matrix}
   0  & 2  & 4  & 6\\
   8  & 10 & 12 & 14\\
   16 & 18 & 20 & 22
   \end{matrix}
   \right]
$$

and 

$$
   X_2 =
   \left[
   \begin{matrix}
   1  & 3  & 5  & 7\\
   9  & 11 & 13 & 15\\
   17 & 19 & 21 & 23
   \end{matrix}
   \right]
$$




С помощью tensorly можно создавать и оперировать тезормаи как с numpy array:

In [2]:
X = tl.tensor(np.arange(24).reshape((3, 4, 2)), dtype=tl.float32)

In [41]:
type(X)

numpy.ndarray

In [42]:
X

array([[[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.]],

       [[ 8.,  9.],
        [10., 11.],
        [12., 13.],
        [14., 15.]],

       [[16., 17.],
        [18., 19.],
        [20., 21.],
        [22., 23.]]], dtype=float32)

Доступ к срезам тензоров доступен в классическом для numpy варианте:

In [4]:
X[:, :, 0]

array([[ 0.,  2.,  4.,  6.],
       [ 8., 10., 12., 14.],
       [16., 18., 20., 22.]], dtype=float32)

In [5]:
X[:, :, 1]

array([[ 1.,  3.,  5.,  7.],
       [ 9., 11., 13., 15.],
       [17., 19., 21., 23.]], dtype=float32)

# 2. Базовые операцции с векторами

## 2.1 Unfolding или развертка

### Напоминание


$\tensor{X} \in \mathbb{R}^{I_1 \times I_2 \times \dots \times I_N}$ - тензор $N$-ого порядка,
индекс $i_n$ пробегает значения $1, \dots, I_n$ для $n = 1, \dots, N$.

Левый мультииндекс (реверсивно-лексикографический):
    $$ \overline{i_1 i_2 \dots i_N} = i_1 + (i_2 - 1)I_1 + (i_3 - 1)I_1 I_2 + \dots + (i_N - 1)I_1 I_2 \dots I_{N-1}$$
    
Развёрткой $n$-ой моды тензора $\tensor{X}$ называется матрица $$\M{X}_{(n)} \in \mathbb{R}^{I_n \times I_1 I_2 \dots I_{n_1} I_{n+1} \dots I_N},$$  
    $$\Big(\M{X}_{(n)}\Big)_{i_n, \overline{i_1 \dots i_{n-1} i_{n+1} \dots i_N}} = x_{i_1, \dots, i_N}$$

### ВАЖНО

Обычно развертка по 1 моде означает развертывание по первому индексу.
Однако, чтобы соответствовать индексации Python, которая всегда начинается с нуля, в тензорном виде развертка тоже начинается с нулевой моды!

Например,  определим $\tensor{X}$ через его срезы:
$$
   X_1 = 
   \left[
   \begin{matrix}
   0  & 2  & 4  & 6\\
   8  & 10 & 12 & 14\\
   16 & 18 & 20 & 22
   \end{matrix}
   \right]
$$
$$
   X_2 =
   \left[
   \begin{matrix}
   1  & 3  & 5  & 7\\
   9  & 11 & 13 & 15\\
   17 & 19 & 21 & 23
   \end{matrix}
   \right]
$$

Тогда развертки представимы в виде:
$$
   \tensor{X}_{[0]} =
   \left[ \begin{matrix}
      0 & 1 & 2 & 3 & 4 & 5 & 6 & 7\\
      8 & 9 & 10 & 11 & 12 & 13 & 14 & 15\\
      16 & 17 & 18 & 19 & 20 & 21 & 22 & 23\\
   \end{matrix} \right]
$$


$$
   \tensor{X}_{[1]} =
   \left[ \begin{matrix}
      0 & 1 & 8 & 9 & 16 & 17\\
      2 & 3 & 10 & 11 & 18 & 19\\
      4 & 5 & 12 & 13 & 20 & 21\\
      6 & 7 & 14 & 15 & 22 & 23\\
   \end{matrix} \right]
$$


$$
   \tensor{X}_{[2]} =
   \left[ \begin{matrix}
      0 & 2 & 4 & 6 & 8 & 10 & 12 & 14 & 16 & 18 & 20 & 22\\
      1 & 3 & 5 & 7 & 9 & 11 & 13 & 15 & 17 & 19 & 21 & 23\\
   \end{matrix} \right]
$$

In [6]:
tl.unfold(X, mode=0)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20., 21., 22., 23.]], dtype=float32)

In [7]:
tl.unfold(X, mode=1)

array([[ 0.,  1.,  8.,  9., 16., 17.],
       [ 2.,  3., 10., 11., 18., 19.],
       [ 4.,  5., 12., 13., 20., 21.],
       [ 6.,  7., 14., 15., 22., 23.]], dtype=float32)

In [8]:
tl.unfold(X, mode=2)

array([[ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22.],
       [ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23.]],
      dtype=float32)

## 2.2 Folding или тензоризация

Операция обратная развертке

In [9]:
unfolding = tl.unfold(X, 1)
original_shape = X.shape
tl.fold(unfolding, mode=1, shape=original_shape)

array([[[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.]],

       [[ 8.,  9.],
        [10., 11.],
        [12., 13.],
        [14., 15.]],

       [[16., 17.],
        [18., 19.],
        [20., 21.],
        [22., 23.]]], dtype=float32)

## 2.3 Свертки по n-ой моде

### Свертка тензора и матрицы

Пример свертки тензора с матрицей по $n$-ой моде. Пусть даны тензор $\tensor{X}$ с индексами $(I_1, I_2, \cdots, I_N)$ и матроица $M$ размерности $(D, I_n)$, тогда сверткой по $n$-ой моде тензора $\tensor{X}$ и матрицы $M$ обочначается $\tensor{X} \times_n M$ с результирующим тензором $(I_1 \times \cdots \times I_{n-1} \times D \times I_{n+1} \cdots \times I_n)$.

In [10]:
M = tl.tensor(np.arange(4*5).reshape((5, 4)))
print(M.shape)

(5, 4)


С учетом индексации в Python вторая мода - это `mode=1`:

In [11]:
X.shape

(3, 4, 2)

In [12]:
res = tl.tenalg.mode_dot(X, M, mode=1)
res.shape

(3, 5, 2)

In [13]:
M = tl.tensor(np.arange(2*5).reshape((5, 2)))
print(M.shape)

res = tl.tenalg.mode_dot(X, M, mode=2)
res.shape

(5, 2)


(3, 4, 5)

### Свертка тензора и вектора

Пример свертки тензора с вектором по $n$-ой моде. Пусть даны тензор $\tensor{X}$ с индексами $(I_1, I_2, \cdots, I_N)$ и вектор $v$ размерности $(I_n)$, тогда сверткой по $n$-ой моде тензора $\tensor{X}$ и вектора $v$ обочначается $\tensor{X} \times_n v$ с результирующим тензором $(I_1 \times \cdots \times I_{n-1} \times I_{n+1} \cdots \times I_n)$.

In [14]:
v = tl.tensor(np.arange(4))
v

array([0, 1, 2, 3])

In [15]:
res = tl.tenalg.mode_dot(X, v, mode=1)

In [16]:
X.shape, res.shape

((3, 4, 2), (3, 2))

In [17]:
res

array([[ 28.,  34.],
       [ 76.,  82.],
       [124., 130.]])

Классическое матричное произведение для numpy

In [18]:
X[:, :, 0] @ v

array([ 28.,  76., 124.])

In [19]:
X[:, :, 1] @ v

array([ 34.,  82., 130.])

# 3. CP decomposition
Canonical Polyadic Decomposition (CP, PARAFAC).

## 3.1 Базовый пример

In [20]:
from tensorly.decomposition import parafac

In [21]:
X = tl.tensor(np.arange(24).reshape((3, 4, 2)), dtype=tl.float32)

In [22]:
weights, factors = parafac(X, rank=1)

In [23]:
weights.shape, len(factors)

((1,), 3)

In [24]:
factors[0].shape, factors[1].shape, factors[2].shape

((3, 1), (4, 1), (2, 1))

И обратное преобразование

In [25]:
[f.shape for f in factors]

[(3, 1), (4, 1), (2, 1)]

In [26]:
full_tensor = tl.cp_to_tensor((weights, factors))
full_tensor.shape

(3, 4, 2)

## 3.2 Пример восстановления внешнего произведения

In [112]:
a = tl.tensor(np.arange(1,5).reshape((4)), dtype=tl.float32)
b = tl.tensor(np.arange(1,5).reshape((4))**2, dtype=tl.float32)
c = tl.tensor(np.arange(1,5).reshape((4))**(1/2), dtype=tl.float32)

X = tl.tenalg.outer([a,a]) + tl.tenalg.outer([b,b]) + tl.tenalg.outer([c,c])

In [113]:
a, b, c

(array([1., 2., 3., 4.], dtype=float32),
 array([ 1.,  4.,  9., 16.], dtype=float32),
 array([1.       , 1.4142135, 1.7320508, 2.       ], dtype=float32))

In [114]:
X

array([[  3.       ,   7.4142137,  13.732051 ,  22.       ],
       [  7.4142137,  22.       ,  44.44949  ,  74.82843  ],
       [ 13.732051 ,  44.44949  ,  93.       , 159.4641   ],
       [ 22.       ,  74.82843  , 159.4641   , 276.       ]],
      dtype=float32)

In [115]:
weights, factors = parafac(X, rank = 3)

In [116]:
weights

array([1., 1., 1.], dtype=float32)

In [117]:
full_tensor = tl.cp_to_tensor((weights, factors))
full_tensor

array([[  2.9999998,   7.414215 ,  13.73205  ,  21.999996 ],
       [  7.4142156,  22.000002 ,  44.449497 ,  74.82844  ],
       [ 13.732052 ,  44.44949  ,  93.       , 159.4641   ],
       [ 22.000002 ,  74.82843  , 159.4641   , 276.       ]],
      dtype=float32)

In [118]:
np.linalg.norm(X-full_tensor)

1.2074906e-05

# 4. Tucker decomposition

In [119]:
from tensorly.decomposition import tucker

In [120]:
X = tl.tensor(np.arange(24).reshape((3, 4, 2)), dtype=tl.float32)
core, factors = tucker(X, rank=[2, 2, 2])
core.shape

(2, 2, 2)

In [121]:
core

array([[[ 6.5527496e+01, -2.8125763e-02],
        [-6.4976215e-03, -3.1402889e-01]],

       [[-2.6830435e-03, -1.1706175e+00],
        [-5.3440847e+00, -3.4387589e-01]]], dtype=float32)

In [122]:
factors

[array([[ 0.16419879,  0.8979823 ],
        [ 0.5055992 ,  0.27875212],
        [ 0.8469995 , -0.3404777 ]], dtype=float32),
 array([[ 0.39653513,  0.7367224 ],
        [ 0.4619288 ,  0.29431573],
        [ 0.5273226 , -0.14809097],
        [ 0.5927162 , -0.5904976 ]], dtype=float32),
 array([[ 0.68415034,  0.72934103],
        [ 0.72934103, -0.68415034]], dtype=float32)]

In [123]:
full_tensor = tl.tucker_to_tensor((core, factors))
full_tensor.shape

(3, 4, 2)

In [124]:
np.linalg.norm(X-full_tensor)

8.12511e-06

In [125]:
a = tl.tensor(np.arange(1,5).reshape((4)), dtype=tl.float32)
b = tl.tensor(np.arange(1,5).reshape((4))**2, dtype=tl.float32)
c = tl.tensor(np.arange(1,5).reshape((4))**(1/2), dtype=tl.float32)

X = tl.tenalg.outer([a,a]) + tl.tenalg.outer([b,b]) + tl.tenalg.outer([c,c])

In [126]:
a, b

(array([1., 2., 3., 4.], dtype=float32),
 array([ 1.,  4.,  9., 16.], dtype=float32))

In [127]:
X

array([[  3.       ,   7.4142137,  13.732051 ,  22.       ],
       [  7.4142137,  22.       ,  44.44949  ,  74.82843  ],
       [ 13.732051 ,  44.44949  ,  93.       , 159.4641   ],
       [ 22.       ,  74.82843  , 159.4641   , 276.       ]],
      dtype=float32)

In [128]:
core, factors = tucker(X, rank=[2, 2])

In [129]:
core

array([[3.9085934e+02, 0.0000000e+00],
       [7.1525574e-06, 3.1225786e+00]], dtype=float32)

In [130]:
full_tensor = tl.tucker_to_tensor((core, factors))
full_tensor

array([[  2.9897604,   7.4180155,  13.738977 ,  21.995785 ],
       [  7.418015 ,  21.998587 ,  44.446922 ,  74.83001  ],
       [ 13.738975 ,  44.44692  ,  92.99531  , 159.46695  ],
       [ 21.995783 ,  74.83     , 159.46695  , 275.9983   ]],
      dtype=float32)

In [131]:
np.linalg.norm(X-full_tensor)

0.018072177